/* =====================================================================
   公园雷达 · 数据层（演示数据，城市与公园均为虚构）
   ===================================================================== */
const CITY = '云栖市';

const CATS = [
    { key: 'all',     label: '全部',   icon: 'CompassIcon' },
    { key: 'family',  label: '亲子',   icon: 'BalloonIcon',   color: 'app-pink' },
    { key: 'flower',  label: '赏花',   icon: 'FlowerIcon',    color: 'warm-peach-pink' },
    { key: 'lake',    label: '湖景',   icon: 'SailboatIcon',  color: 'app-blue' },
    { key: 'forest',  label: '森林',   icon: 'TreeIcon',      color: 'app-green' },
    { key: 'camp',    label: '露营',   icon: 'TentIcon',      color: 'app-orange' },
    { key: 'pet',     label: '宠物',   icon: 'DogIcon',       color: 'app-yellow' },
    { key: 'sport',   label: '运动',   icon: 'BasketballIcon', color: 'lime-green' },
    { key: 'culture', label: '文化',   icon: 'BookIcon',      color: 'purple' },
    { key: 'wetland', label: '湿地',   icon: 'BirdIcon',      color: 'app-teal' },
];
const catMeta = (k) => CATS.find(c => c.key === k) || CATS[0];

const SORTS = [
    { key: 'rec',      label: '综合推荐' },
    { key: 'rating',   label: '评分最高' },
    { key: 'distance', label: '离我最近' },
    { key: 'quiet',    label: '人少清净' },
    { key: 'free',     label: '免费开放' },
];

const PARKS = [
    {
        id: 'p1', name: '翠湖湿地公园', cat: 'wetland', rating: 4.8, reviews: 2341,
        distance: 2.3, area: 86, open: '06:00', close: '21:30',
        ticket: 0, ticketNote: '免费 · 需预约', crowd: 2,
        crowdWeek: [2, 2, 2, 3, 3, 5, 4],
        address: '滨江区翠湖路 88 号', district: '滨江区',
        features: ['环湖木栈道', '观鸟屋', '划船', '骑行', '免费停车'],
        tags: ['遛娃', '拍照', '日落', '野餐', '观鸟'],
        desc: '城市里难得的原生态湿地，4 公里环湖木栈道串起芦苇荡、观鸟屋与湖心岛。清晨薄雾未散时，白鹭从水面掠过的瞬间是这里最出名的画面。',
        highlights: ['4 公里环湖木栈道，全程无障碍通行', '秋冬季节超过 60 种候鸟在此栖息', '湖心岛观景台是看日落的黄金机位'],
        best: '3-5 月 / 9-11 月',
        tips: '周末上午 10 点后人流明显增多，观鸟建议 8 点前入园；观鸟屋需在现场扫码预约。',
        seed: 11,
        scene: { type: 'wetland', sky: ['#cdeef5', '#eaf7ee'], sun: '#ffe9a8', hills: ['#8fc9b8', '#5fae9c', '#3f8e82'], water: '#8ed0dd' },
        facilities: [
            { icon: 'CarIcon', label: '免费停车' }, { icon: 'SmileIcon', label: '无障碍' },
            { icon: 'SailboatIcon', label: '游船' }, { icon: 'BirdIcon', label: '观鸟屋' },
            { icon: 'WifiIcon', label: 'WiFi' }, { icon: 'WaterCupIcon', label: '直饮水' },
            { icon: 'BicycleIcon', label: '租车骑行' }, { icon: 'CameraIcon', label: '拍照点' },
        ],
        comments: [
            { user: '白鹭与晚风', icon: 'BirdIcon', bg: 'pattern-app-teal', text: '早上七点到的，雾还没散，木栈道上只有我和几只白鹭，安静得像另一个世界。', time: '3 天前', likes: 46 },
            { user: '阿栗', icon: 'RabbitIcon', bg: 'pattern-app-pink', text: '带 4 岁娃来划船，栈道推婴儿车完全没压力，观鸟屋里小朋友看望远镜看了半小时不肯走。', time: '1 周前', likes: 31 },
            { user: 'Lens大叔', icon: 'FoxIcon', bg: 'pattern-app-orange', text: '日落时分的湖心岛，金色洒满水面，出片率极高。建议带长焦。', time: '2 周前', likes: 58 },
        ],
        faq: [
            ['需要提前预约吗？', '需要。通过「云栖公园」小程序提前 1-3 天免费预约，周末名额紧张建议提前抢。'],
            ['可以带宠物吗？', '为保护鸟类栖息环境，园区全域禁止宠物入内，敬请谅解。'],
            ['停车场收费吗？', '南门与北门停车场对预约游客免费，共 300 个车位，周末 9 点后基本满位。'],
        ],
    },
    {
        id: 'p2', name: '樱语谷公园', cat: 'flower', rating: 4.9, reviews: 3892,
        distance: 5.1, area: 42, open: '07:00', close: '20:00',
        ticket: 20, ticketNote: '¥20 · 花季限行', crowd: 4,
        crowdWeek: [3, 3, 4, 4, 5, 5, 5],
        address: '栖霞区樱语谷路 1 号', district: '栖霞区',
        features: ['千株樱花', '草坪野餐', '拍照打卡', '花海', '周末市集'],
        tags: ['樱花', '约会', '出片', '春日', '野餐'],
        desc: '整条山谷种满三千株樱花，从早樱到晚樱花期接力近两个月。花瓣落在溪水上顺流而下，是全城春天最盛大的一场花事。',
        highlights: ['早樱/中樱/晚樱三季接力，花期从 3 月初到 4 月底', '樱溪步道：花瓣随溪水漂流的招牌景观', '山顶草坪可野餐，俯瞰整片花海'],
        best: '3 月 - 4 月',
        tips: '花季周末实行限流，务必线上购票；工作日清晨 7-9 点人最少，逆光拍樱花正好。',
        seed: 23,
        scene: { type: 'sakura', sky: ['#ffe3ee', '#fff4e8'], sun: '#fff0c2', hills: ['#f0b3c8', '#e287a6', '#c96a90'] },
        facilities: [
            { icon: 'CarIcon', label: '停车场' }, { icon: 'IcecreamIcon', label: '冰淇淋车' },
            { icon: 'FlagIcon', label: '打卡点' }, { icon: 'CoffeeIcon', label: '咖啡' },
            { icon: 'CameraIcon', label: '拍照点' }, { icon: 'MapIcon', label: '导览图' },
            { icon: 'WaterCupIcon', label: '直饮水' }, { icon: 'SmileIcon', label: '母婴室' },
        ],
        comments: [
            { user: '春日部防卫队', icon: 'CatIcon', bg: 'pattern-app-pink', text: '满开那天去的，风一吹就是樱花雨，虽然人多但真的值！山顶草坪野餐记得带垫子。', time: '2 个月前', likes: 122 },
            { user: 'momo', icon: 'PenguinIcon', bg: 'pattern-app-blue', text: '工作日上午请假来的，整条樱溪步道几乎包场，拍照不用等位，血赚。', time: '1 个月前', likes: 87 },
            { user: '老周', icon: 'BearIcon', bg: 'pattern-brown', text: '带父母来的，坡道有点多，建议从东门坐摆渡车上山再往下走。', time: '3 周前', likes: 40 },
        ],
        faq: [
            ['门票多少？', '平日 ¥20，花季（3-4 月）周末 ¥30，1.2 米以下儿童与 65 岁以上老人免票。'],
            ['花季会限流吗？', '会。花季周末每日限流 8000 人，需提前在官方小程序购票预约时段。'],
            ['除了春天还值得来吗？', '夏季有溪涧玩水区，秋季红枫谷同样出名，冬季樱树干上有灯光装置。'],
        ],
    },
    {
        id: 'p3', name: '松果岭森林公园', cat: 'forest', rating: 4.7, reviews: 1876,
        distance: 8.4, area: 320, open: '06:30', close: '19:00',
        ticket: 10, ticketNote: '¥10 · 全年', crowd: 2,
        crowdWeek: [1, 1, 2, 2, 3, 4, 4],
        address: '云岭区松果岭道 66 号', district: '云岭区',
        features: ['登山步道', '观景台', '松林氧吧', '露营地', '索道'],
        tags: ['徒步', '吸氧', '避暑', '秋色', '观星'],
        desc: '三百公顷的松林覆盖着起伏的山岭，登顶观景台可以望见整座城。夏天比市区低 4 度，是全城人私藏的避暑后花园。',
        highlights: ['三条难度分级步道：亲子线 2km / 挑战线 6km / 穿越线 11km', '山顶观景台日落时分可见城市天际线全景', '松林营地夜间光污染极低，适合观星'],
        best: '5-10 月',
        tips: '山路部分路段较陡，请穿防滑运动鞋；山顶风大，傍晚看日落记得带外套。',
        seed: 37,
        scene: { type: 'forest', sky: ['#dcefd2', '#f4f8e0'], sun: '#ffe9a8', hills: ['#9cc98a', '#6fae63', '#4e8a4a'] },
        facilities: [
            { icon: 'CarIcon', label: '停车场' }, { icon: 'MountainIcon', label: '登山道' },
            { icon: 'TentIcon', label: '营地' }, { icon: 'WaterCupIcon', label: '补给站' },
            { icon: 'RocketIcon', label: '观景台' }, { icon: 'StarIcon', label: '观星点' },
            { icon: 'MapIcon', label: '导览图' }, { icon: 'SmileIcon', label: '急救点' },
        ],
        comments: [
            { user: '徒步的蜗牛', icon: 'SnailIcon', bg: 'pattern-app-green', text: '穿越线走完全程 4 小时，沿途松涛声太治愈了。补给站间隔合理，带 1L 水足够。', time: '5 天前', likes: 39 },
            { user: 'Yoyo妈', icon: 'RabbitIcon', bg: 'pattern-app-pink', text: '亲子线很适合小朋友，2 公里全程缓坡，娃一路捡松果开心到飞起。', time: '2 周前', likes: 52 },
            { user: '星空猎人K', icon: 'OwlIcon', bg: 'pattern-purple', text: '上周六在松林营地拍到了银河拱桥，市区过来 40 分钟就有这种夜空，感动。', time: '1 个月前', likes: 96 },
        ],
        faq: [
            ['索道怎么收费？', '单程 ¥30，往返 ¥50，运营时间 8:30-17:00，大风天气停运。'],
            ['可以带狗吗？', '可以，需全程牵绳；营地与观景台区域禁止宠物进入。'],
            ['夜间开放吗？', '19:00 清场，但预约观星活动的团队可停留至 22:00（需自备照明）。'],
        ],
    },
    {
        id: 'p4', name: '星野露营基地', cat: 'camp', rating: 4.6, reviews: 967,
        distance: 12.6, area: 58, open: '全天', close: '开放',
        ticket: 45, ticketNote: '¥45 · 营位起', crowd: 3,
        crowdWeek: [2, 2, 2, 3, 4, 5, 4],
        address: '云岭区星野镇环山路 9 号', district: '云岭区',
        features: ['篝火晚会', '帐篷草坪', '烧烤区', '观星', '宠物友好'],
        tags: ['露营', '过夜', '篝火', '周末', '遛狗'],
        desc: '山坡上的帐篷营地，白天是草坪与山风，夜晚是篝火与银河。提供拎包入住的精致营位，也欢迎自带装备的老玩家。',
        highlights: ['每晚 20:00 篝火晚会，可烤棉花糖', '拎包入住营位含帐篷/防潮垫/氛围灯', '山坡朝向正南，冬季银河肉眼可见'],
        best: '4-6 月 / 9-11 月',
        tips: '山区昼夜温差大，即使夏天也建议带抓绒外套；烧烤区需单独预约，禁止在草坪直接用明火。',
        seed: 41,
        scene: { type: 'camp', sky: ['#ffd9a0', '#ffbc8e'], sun: '#ff9d5c', hills: ['#c98a5e', '#a06840', '#7a4c2e'] },
        facilities: [
            { icon: 'TentIcon', label: '帐篷营位' }, { icon: 'FlameIcon', label: '篝火区' },
            { icon: 'CarIcon', label: '自驾营地' }, { icon: 'DogIcon', label: '宠物友好' },
            { icon: 'StarIcon', label: '观星草坪' }, { icon: 'WaterCupIcon', label: '洗漱间' },
            { icon: 'WifiIcon', label: 'WiFi' }, { icon: 'LampIcon', label: '夜间照明' },
        ],
        comments: [
            { user: '帐篷不打钉', icon: 'FoxIcon', bg: 'pattern-app-orange', text: '精致营位真的省心，灯串一挂氛围直接拉满。篝火晚会有工作人员带节奏，社恐也能玩起来。', time: '1 周前', likes: 44 },
            { user: '大狗子的小跟班', icon: 'DogIcon', bg: 'pattern-app-yellow', text: '带金毛来的，宠物营地在东侧单独一片，狗子撒欢了一整晚。', time: '3 周前', likes: 37 },
            { user: 'Nana', icon: 'ButterflyIcon', bg: 'pattern-purple', text: '10 月底来的，夜里真的看到了银河！就是有点冷，羽绒服都用上了。', time: '2 个月前', likes: 61 },
        ],
        faq: [
            ['可以自带帐篷吗？', '可以，自带装备营位 ¥45/顶，含公共卫浴与篝火晚会；精致营位 ¥299 起含全套装备与早餐。'],
            ['下雨天怎么办？', '小雨正常运营并发放防雨装备，暴雨/大风预警可全额改期或退款。'],
            ['有电源吗？', '精致营位含电源接口，自带营位可使用公共充电柜（扫码付费）。'],
        ],
    },
    {
        id: 'p5', name: '泡泡鱼儿童公园', cat: 'family', rating: 4.8, reviews: 4210,
        distance: 1.8, area: 24, open: '08:00', close: '20:00',
        ticket: 0, ticketNote: '免费开放', crowd: 5,
        crowdWeek: [3, 3, 3, 4, 4, 5, 5],
        address: '新城区泡泡路 18 号', district: '新城区',
        features: ['巨型滑梯', '沙池', '戏水区', '母婴室', '婴儿车租赁'],
        tags: ['遛娃', '儿童', '亲子', '就近', '戏水'],
        desc: '为 2-12 岁孩子打造的放电圣地：巨型章鱼滑梯、白沙池、夏季戏水区一应俱全。离地铁站只有 300 米，是就近遛娃的首选。',
        highlights: ['12 米高巨型章鱼滑梯，分龄三条滑道', '白沙池配备挖沙工具免费借用', '夏季戏水区 6-8 月开放，水深仅 20cm'],
        best: '全年（夏季戏水）',
        tips: '周末下午 2-5 点是高峰，滑梯需排队；沙池旁有冲脚池，给娃备一双拖鞋和换洗衣物。',
        seed: 53,
        scene: { type: 'playground', sky: ['#bfe9f7', '#fdf6dd'], sun: '#ffd97a', hills: ['#a5d8a0', '#7cc57f', '#5aa862'] },
        facilities: [
            { icon: 'BalloonIcon', label: '游乐区' }, { icon: 'SmileIcon', label: '母婴室' },
            { icon: 'WaterCupIcon', label: '戏水池' }, { icon: 'IcecreamIcon', label: '小卖部' },
            { icon: 'UmbrellaIcon', label: '遮阳棚' }, { icon: 'WifiIcon', label: 'WiFi' },
            { icon: 'TrainIcon', label: '小火车' }, { icon: 'DumbbellIcon', label: '家长健身角' },
        ],
        comments: [
            { user: '二胎奶爸老K', icon: 'BearIcon', bg: 'pattern-app-yellow', text: '家门口的遛娃神地，滑梯分龄设计很科学，2 岁的玩小滑道，7 岁的冲大滑道，互不干扰。', time: '2 天前', likes: 78 },
            { user: '团团妈', icon: 'CatIcon', bg: 'pattern-app-pink', text: '戏水区水深只到脚踝，家长可以放心坐在边上看。记得带泳圈和替换衣服！', time: '1 周前', likes: 55 },
            { user: '幼儿园张老师', icon: 'OwlIcon', bg: 'pattern-app-teal', text: '带班上来秋游，工作人员会主动帮忙维持秩序，沙池工具免费借这点太贴心。', time: '1 个月前', likes: 43 },
        ],
        faq: [
            ['需要预约吗？', '免费免预约，但戏水区（6-8 月）需现场领取限量手环，建议上午 10 点前到。'],
            ['有适合小月龄宝宝的区域吗？', '有，北侧「泡泡湾」为 0-3 岁专属软包区，与滑梯区物理隔离。'],
            ['公园里有餐食吗？', '小卖部提供简餐与冰品，也可自带食物在遮阳棚野餐区食用。'],
        ],
    },
    {
        id: 'p6', name: '云汀湿地', cat: 'wetland', rating: 4.7, reviews: 1243,
        distance: 6.2, area: 140, open: '07:00', close: '18:30',
        ticket: 0, ticketNote: '免费开放', crowd: 1,
        crowdWeek: [1, 1, 1, 1, 2, 3, 3],
        address: '江湾区云汀半岛', district: '江湾区',
        features: ['观鸟屋', '水上森林', '安静垂钓', '自然课堂', '木栈道'],
        tags: ['安静', '观鸟', '拍照', '工作日', '发呆'],
        desc: '一片几乎没有游客的水上森林，池杉长在浅水里，木栈道蜿蜒其间。这里是全城观鸟协会的定点观测站，也是「想一个人静静」的最佳去处。',
        highlights: ['水上池杉林，秋季叶片锈红色倒影极美', '记录在册鸟类 143 种，观鸟屋备有公共望远镜', '自然课堂每周末有免费导览（需报名）'],
        best: '10-12 月（池杉季）',
        tips: '园区刻意保留了静谧环境，无广播无音乐；请轻声慢行。蚊虫较多，务必带驱蚊水。',
        seed: 67,
        scene: { type: 'marsh', sky: ['#e2eee6', '#f2f7ef'], sun: '#fff4d0', hills: ['#a8c4b0', '#7fa88d', '#5d8a70'], water: '#9dc4c9' },
        facilities: [
            { icon: 'BirdIcon', label: '观鸟屋' }, { icon: 'BookIcon', label: '自然课堂' },
            { icon: 'FishIcon', label: '垂钓区' }, { icon: 'MapIcon', label: '导览图' },
            { icon: 'WaterCupIcon', label: '直饮水' }, { icon: 'CarIcon', label: '小型停车场' },
        ],
        comments: [
            { user: '静音模式', icon: 'SnailIcon', bg: 'pattern-app-teal', text: '工作日下午来发呆两小时，全程只遇到三个人和一只翠鸟。这种公园请多来点。', time: '4 天前', likes: 89 },
            { user: '鸟类图鉴收集者', icon: 'OwlIcon', bg: 'pattern-app-blue', text: '上周观测到 11 种鸟，观鸟屋的公共望远镜保养得很好，视野清晰。', time: '2 周前', likes: 64 },
            { user: '秋刀鱼', icon: 'FishIcon', bg: 'pattern-warm-peach-pink', text: '11 月底池杉全红的时候来的，倒影绝了，随手拍都是壁纸。', time: '3 个月前', likes: 71 },
        ],
        faq: [
            ['为什么这么安静？', '园区定位生态保育型湿地，不设游乐设施与广播系统，限流保护鸟类栖息。'],
            ['自然课堂怎么报名？', '每周六上午 9:30 免费导览，「云汀湿地」公众号每周三放号，每期 20 人。'],
            ['可以钓鱼吗？', '东侧垂钓区可以（需办理免费垂钓证），核心区全年禁钓。'],
        ],
    },
    {
        id: 'p7', name: '风荷园', cat: 'lake', rating: 4.5, reviews: 2087,
        distance: 3.4, area: 36, open: '06:00', close: '21:00',
        ticket: 5, ticketNote: '¥5 · 老年卡免票', crowd: 3,
        crowdWeek: [2, 2, 3, 3, 4, 5, 4],
        address: '临湖区风荷巷 22 号', district: '临湖区',
        features: ['荷花池', '九曲桥', '赏月亭', '划船', '夜荷灯'],
        tags: ['荷花', '夏夜', '划船', '复古', '赏月'],
        desc: '老临湖人记忆里的荷园，夏天满池「接天莲叶无穷碧」。九曲桥、石舫、赏月亭都是上世纪的园林手法，晚上亮起暖黄的夜荷灯，别有味道。',
        highlights: ['6-8 月荷花盛放，清晨 5-7 点荷香最浓', '九曲桥尽头石舫可喝茶，10 元一位续水免费', '中秋赏月亭有民乐演奏（免费）'],
        best: '6-8 月',
        tips: '划船按小时计费（¥60/小时押金另付），傍晚场最抢手建议 4 点前去租；荷花池边蚊虫多。',
        seed: 71,
        scene: { type: 'lotus', sky: ['#e8f4e0', '#fdf3dd'], sun: '#ffe9a8', hills: ['#a5cf93', '#7cb56f', '#5f9a58'], water: '#8ec9c0' },
        facilities: [
            { icon: 'SailboatIcon', label: '划船' }, { icon: 'CoffeeIcon', label: '石舫茶座' },
            { icon: 'LampIcon', label: '夜荷灯' }, { icon: 'MoonIcon', label: '赏月亭' },
            { icon: 'MapIcon', label: '导览图' }, { icon: 'CarIcon', label: '路侧停车' },
        ],
        comments: [
            { user: '外婆的蒲扇', icon: 'BearIcon', bg: 'pattern-app-green', text: '从小跟着外婆来的园子，石舫喝茶还是 10 块钱，荷花还是那个荷花，情怀满分。', time: '6 天前', likes: 103 },
            { user: '夜景摄影师Leo', icon: 'CameraIcon', bg: 'pattern-purple', text: '夜荷灯亮起后拍照氛围绝了，暖黄灯光配荷叶，长曝光 2 秒出大片。', time: '3 周前', likes: 47 },
            { user: '划船不翻', icon: 'FrogIcon', bg: 'pattern-lime-green', text: '傍晚划船看日落强烈推荐，就是记得 4 点前去排队，我们 5 点到等了 40 分钟。', time: '1 个月前', likes: 35 },
        ],
        faq: [
            ['门票优惠政策？', '全票 ¥5；60 岁以上凭老年卡、1.2 米以下儿童免票。'],
            ['划船多少钱？', '脚踏船 ¥60/小时（押金 ¥200），电动船 ¥100/小时，17:30 停止租船。'],
            ['冬天有什么看的？', '冬季有残荷景观与腊梅园，石舫茶座供应热姜茶，别有意境。'],
        ],
    },
    {
        id: 'p8', name: '橡果坡宠物乐园', cat: 'pet', rating: 4.9, reviews: 1532,
        distance: 4.0, area: 18, open: '08:30', close: '21:00',
        ticket: 0, ticketNote: '免费 · 宠物需登记', crowd: 3,
        crowdWeek: [2, 2, 3, 3, 4, 5, 5],
        address: '新城区橡果坡 7 号', district: '新城区',
        features: ['狗狗跑道', '宠物泳池', '洗护站', '遮阴草坪', '宠物咖啡'],
        tags: ['遛狗', '宠物', '社交', '草坪', '撒欢'],
        desc: '全城毛孩子的快乐老家：环形跑道、夏季宠物泳池、自助洗护站，还有一间可以带狗进店的宠物咖啡。大型犬与小型犬分区活动，主人也能安心社交。',
        highlights: ['800 米环形塑胶跑道，夜场有地灯', '大/小型犬物理分区，避免冲突', '自助洗护站 ¥20/次含吹干，24 小时可用'],
        best: '全年',
        tips: '入园需出示疫苗本并佩戴牵引绳（分区内可解开）；泳池仅夏季开放，下水前请先冲洗。',
        seed: 83,
        scene: { type: 'meadow', sky: ['#fff3c9', '#ffe9b0'], sun: '#ffdf70', hills: ['#b5dc7e', '#8cc765', '#6aa84f'] },
        facilities: [
            { icon: 'DogIcon', label: '狗狗跑道' }, { icon: 'WaterCupIcon', label: '宠物泳池' },
            { icon: 'CoffeeIcon', label: '宠物咖啡' }, { icon: 'UmbrellaIcon', label: '遮阴草坪' },
            { icon: 'LampIcon', label: '夜场灯' }, { icon: 'SmileIcon', label: '洗护站' },
            { icon: 'CarIcon', label: '停车场' }, { icon: 'WifiIcon', label: 'WiFi' },
        ],
        comments: [
            { user: '柯基屁股蛋', icon: 'DogIcon', bg: 'pattern-app-yellow', text: '小型犬区的草坪维护得很好，我家柯基每次来都玩到不肯走。洗护站 20 块真香。', time: '2 天前', likes: 66 },
            { user: '金毛大暖男', icon: 'BearIcon', bg: 'pattern-app-orange', text: '大型犬区终于不用跟小狗狗挤了，800 米跑道撒开了跑，晚上有灯夏天凉快时候来正好。', time: '1 周前', likes: 48 },
            { user: '猫也想过来', icon: 'CatIcon', bg: 'pattern-purple', text: '宠物咖啡可以带猫包进店，店员会帮忙看顾，狗区猫区分时段，细节好评。', time: '3 周前', likes: 39 },
        ],
        faq: [
            ['需要什么手续入园？', '首次入园登记疫苗本 + 犬牌，之后刷登记的二维码即可；猫咪需使用猫包或牵引绳。'],
            ['有宠物寄养吗？', '有短时寄养（¥30/2 小时，含监控直播），需提前一天预约。'],
            ['下雨天开放吗？', '小雨正常开放（有遮雨棚活动区），暴雨天气闭园并在公众号提前通知。'],
        ],
    },
    {
        id: 'p9', name: '萤火森林公园', cat: 'forest', rating: 4.6, reviews: 1105,
        distance: 9.3, area: 210, open: '08:00', close: '22:00',
        ticket: 25, ticketNote: '日场免费 · 夜游 ¥25', crowd: 2,
        crowdWeek: [1, 1, 2, 2, 3, 4, 4],
        address: '云岭区萤火谷路', district: '云岭区',
        features: ['萤火虫谷', '夜游步道', '灯光森林', '自然观测', '科普馆'],
        tags: ['夜景', '萤火虫', '夏季', '亲子科普', '夜游'],
        desc: '白天安静的森林公园，入夜后是另一个世界：6-7 月萤火虫谷漫天流萤，全年开放的灯光森林把树冠染成蓝紫色。夜游步道全程有安全员巡逻。',
        highlights: ['6-7 月萤火虫谷限定开放，每晚限 200 人', '灯光森林装置由本地美院团队创作，四季换主题', '科普馆晚间有「夜行生物」专场讲解'],
        best: '6-7 月（萤火虫）',
        tips: '萤火虫谷禁止使用闪光灯与白光手电（入口发放红光头灯）；夜游 20:00 停止入场。',
        seed: 97,
        scene: { type: 'night', sky: ['#3d4a80', '#889df0'], sun: '#fff6d8', hills: ['#33406e', '#26315a', '#1c2547'], moon: true },
        facilities: [
            { icon: 'MoonIcon', label: '夜游步道' }, { icon: 'LampIcon', label: '灯光森林' },
            { icon: 'BookIcon', label: '科普馆' }, { icon: 'BeeIcon', label: '萤火谷' },
            { icon: 'SmileIcon', label: '安全员' }, { icon: 'CarIcon', label: '停车场' },
            { icon: 'WaterCupIcon', label: '补给点' }, { icon: 'CameraIcon', label: '拍照点' },
        ],
        comments: [
            { user: '追萤人', icon: 'BeeIcon', bg: 'pattern-app-yellow', text: '6 月底抢到了萤火虫谷名额，孩子看到漫天流萤那一刻眼睛都亮了，值回所有等待。', time: '2 个月前', likes: 134 },
            { user: '夜猫子小姐', icon: 'CatIcon', bg: 'pattern-app-blue', text: '灯光森林拍照太出片了，蓝紫色树冠配暖黄地灯，随手拍都是梦幻感。', time: '3 周前', likes: 57 },
            { user: '安全观察员', icon: 'OwlIcon', bg: 'pattern-app-teal', text: '步道照明和管理都到位，带 6 岁娃夜走 3 公里完全放心。红光头灯细节满分。', time: '1 个月前', likes: 41 },
        ],
        faq: [
            ['日场和夜场是分开的票吗？', '日场（8:00-18:00）免费；夜游（18:30-22:00）¥25，萤火虫谷需另抢限定名额（含在夜游票内）。'],
            ['萤火虫季怎么预约？', '每年 6 月初公众号放出 6-7 月名额，每晚 200 人，通常 10 分钟内抢完。'],
            ['夜游安全吗？', '主步道全程有地灯与反光标识，每 500 米设安全员岗亭，可放心带儿童前往。'],
        ],
    },
    {
        id: 'p10', name: '潮汐湾运动公园', cat: 'sport', rating: 4.4, reviews: 1738,
        distance: 7.7, area: 45, open: '06:00', close: '22:30',
        ticket: 0, ticketNote: '免费 · 球场低收费', crowd: 4,
        crowdWeek: [4, 4, 4, 4, 5, 5, 4],
        address: '江湾区潮汐湾大道 1 号', district: '江湾区',
        features: ['滨江跑道', '篮球场', '滑板公园', '骑行道', '灯光球场'],
        tags: ['跑步', '骑行', '篮球', '滑板', '夜练'],
        desc: '沿着江湾铺开的运动带：5 公里滨江跑道、6 片灯光篮球场、碗池滑板公园。傍晚江风一起，整座城的运动青年都往这儿聚集。',
        highlights: ['5 公里滨江跑道，每 500 米有配速打卡牌', '灯光球场开放至 22:30，¥10/人不限时', '碗池滑板区每周六有免费新手教学'],
        best: '全年',
        tips: '篮球场高峰在 19-21 点，可小程序提前锁场；跑道夜段照明良好但江边风大，冬天注意防风。',
        seed: 101,
        scene: { type: 'river', sky: ['#ffd9c2', '#ffc9a8'], sun: '#ff8d6b', hills: ['#c9a08a', '#a87f6e', '#8a6355'], water: '#e8a87c' },
        facilities: [
            { icon: 'DumbbellIcon', label: '健身区' }, { icon: 'BasketballIcon', label: '篮球场' },
            { icon: 'BicycleIcon', label: '骑行道' }, { icon: 'RocketIcon', label: '滑板碗池' },
            { icon: 'LampIcon', label: '灯光球场' }, { icon: 'WaterCupIcon', label: '补给站' },
            { icon: 'CarIcon', label: '停车场' }, { icon: 'WifiIcon', label: 'WiFi' },
        ],
        comments: [
            { user: '五分速跑者', icon: 'RabbitIcon', bg: 'pattern-lime-green', text: '滨江跑道 5 公里一圈正好，配速牌设计得很有仪式感，刷 PB 圣地。', time: '3 天前', likes: 51 },
            { user: '滑板少年阿飞', icon: 'FlameIcon', bg: 'pattern-app-orange', text: '碗池维护得好，周六新手教学的大哥很耐心，从零学会了下坡。', time: '1 周前', likes: 44 },
            { user: '野球场老王', icon: 'BearIcon', bg: 'pattern-brown', text: '灯光球场 10 块钱打到 22 点半，性价比无敌，就是热门时段要提前锁场。', time: '2 周前', likes: 38 },
        ],
        faq: [
            ['球场怎么预约？', '「潮汐湾运动」小程序提前 24 小时放场，¥10/人不限时，可拼场。'],
            ['有淋浴设施吗？', '体育中心一楼有淋浴间（¥8/次），6:00-22:00 开放。'],
            ['滑板区需要护具吗？', '碗池区强制佩戴头盔，新手区建议护膝护肘；现场可租（¥15/套）。'],
        ],
    },
    {
        id: 'p11', name: '竹里馆文化园', cat: 'culture', rating: 4.8, reviews: 876,
        distance: 2.9, area: 12, open: '09:00', close: '17:30',
        ticket: 0, ticketNote: '免费 · 周一闭馆', crowd: 1,
        crowdWeek: [0, 1, 1, 1, 2, 3, 3],
        address: '临湖区竹里巷 5 号', district: '临湖区',
        features: ['竹林书屋', '书画展', '茶室', '古戏台', '安静庭院'],
        tags: ['安静', '看书', '喝茶', '展览', '古风'],
        desc: '藏在老巷子里的园子，竹林深处有间人人可进的书屋。常设本地书画家作品展，古戏台周末偶有昆曲清唱。时间在这里会慢半拍。',
        highlights: ['竹林书屋藏书 8000 册，可带自己的书来交换', '每月更换一次书画展，均为本地创作者', '周六下午古戏台昆曲清唱（免费，20 座）'],
        best: '全年',
        tips: '周一闭馆别跑空；书屋内请静音，戏台演出建议 13:40 前到才有座位。',
        seed: 113,
        scene: { type: 'bamboo', sky: ['#e9f2dd', '#f7f9ec'], sun: '#fff4d0', hills: ['#a9c98f', '#87b06e', '#5f8a4e'] },
        facilities: [
            { icon: 'BookIcon', label: '竹林书屋' }, { icon: 'CoffeeIcon', label: '茶室' },
            { icon: 'PencilIcon', label: '书画展' }, { icon: 'MusicIcon', label: '古戏台' },
            { icon: 'LeafIcon', label: '竹林径' }, { icon: 'MapIcon', label: '导览' },
        ],
        comments: [
            { user: '一茶一书', icon: 'OwlIcon', bg: 'pattern-lime-green', text: '竹林书屋是我在这座城市的「精神充电站」，靠窗位置看竹影摇晃，能坐一下午。', time: '5 天前', likes: 72 },
            { user: '昆曲小白', icon: 'ButterflyIcon', bg: 'pattern-purple', text: '周六误打误撞赶上戏台清唱，20 个座位的小场子，演员离你两米远，鸡皮疙瘩起来了。', time: '2 周前', likes: 58 },
            { user: '写字的猫', icon: 'CatIcon', bg: 'pattern-app-teal', text: '本月展览是本地水彩画家的老城系列，有几张画的就是竹里巷本身，很有共鸣。', time: '1 个月前', likes: 45 },
        ],
        faq: [
            ['需要预约吗？', '平日免预约；书画展开幕日与戏台演出日建议公众号预约。'],
            ['可以带小朋友吗？', '欢迎，书屋有儿童绘本角；请引导孩子保持轻声。'],
            ['茶室消费多少？', '自助茶位 ¥15/位不限时，提供本地绿茶与桂花红茶。'],
        ],
    },
    {
        id: 'p12', name: '蜜糖梅子园', cat: 'flower', rating: 4.5, reviews: 1421,
        distance: 10.5, area: 66, open: '08:00', close: '18:00',
        ticket: 30, ticketNote: '¥30 · 含采摘 1 斤', crowd: 3,
        crowdWeek: [2, 2, 3, 3, 4, 5, 5],
        address: '栖霞区蜜糖镇梅子坞', district: '栖霞区',
        features: ['梅子采摘', '梅酒工坊', '花田野餐', '儿童迷宫', '农夫市集'],
        tags: ['采摘', '亲子', '周末', '春野餐', '市集'],
        desc: '春看梅花秋收梅子的果园。3 月漫山梅花开成粉白云海，6 月梅子黄时全家挎着篮子来采摘，园子里的梅酒工坊可以现场封存一坛属于今年的味道。',
        highlights: ['6 月梅子采摘季：门票含 1 斤采摘额度', '梅酒工坊现场教学，封坛可寄存一年后来取', '儿童树篱迷宫 + 农夫市集（周末限定）'],
        best: '3 月（梅花）/ 6 月（采摘）',
        tips: '采摘季周末 9 点前到果最干净；穿深色衣服，梅子汁很难洗；工坊体验需另付 ¥68。',
        seed: 127,
        scene: { type: 'orchard', sky: ['#fdf0d5', '#ffe9e0'], sun: '#ffe9a8', hills: ['#c5d86f', '#a3c55e', '#82a84a'] },
        facilities: [
            { icon: 'AppleIcon', label: '采摘园' }, { icon: 'BasketballIcon', label: '儿童迷宫' },
            { icon: 'CoffeeIcon', label: '梅子茶铺' }, { icon: 'IcecreamIcon', label: '梅子冰' },
            { icon: 'CarIcon', label: '免费停车' }, { icon: 'GiftIcon', label: '农夫市集' },
            { icon: 'UmbrellaIcon', label: '野餐棚' }, { icon: 'SmileIcon', label: '母婴室' },
        ],
        comments: [
            { user: '梅子酒鬼', icon: 'FoxIcon', bg: 'pattern-app-yellow', text: '去年封的梅酒今年取出来了，开坛那一下满屋香。仪式感拉满的年更项目。', time: '1 周前', likes: 83 },
            { user: '野餐垫常驻民', icon: 'RabbitIcon', bg: 'pattern-app-pink', text: '3 月梅花开的时候在花田野餐，风一吹花瓣落在饭盒里，浪漫得不像话。', time: '5 个月前', likes: 67 },
            { user: '迷宫破解者', icon: 'SnailIcon', bg: 'pattern-app-green', text: '带娃来采摘，结果大人在树篱迷宫里玩得比孩子还开心……', time: '2 个月前', likes: 54 },
        ],
        faq: [
            ['门票包含什么？', '¥30 入园含 1 斤梅子采摘额度（3 月为梅花观赏票），超出部分 ¥15/斤。'],
            ['梅酒工坊怎么玩？', '¥68/人含玻璃坛与基酒，现场教学封坛，可寄存园中一年后自取或邮寄。'],
            ['有餐厅吗？', '梅子茶铺提供简餐与特色梅子冰，周末农夫市集有本地农户小吃摊。'],
        ],
    },
];

const PARK_BY_ID = Object.fromEntries(PARKS.map(p => [p.id, p]));

/* 今日在 crowdWeek（周一为首）中的下标 */
function todayIdx() {
    const d = new Date().getDay();
    return d === 0 ? 6 : d - 1;
}
const WEEK_LABELS = ['一', '二', '三', '四', '五', '六', '日'];

/* 通知数据（演示） */
const NOTICES = [
    { icon: 'FlowerIcon', color: '#f8a6b2', title: '樱语谷公园进入盛花期', text: '本周开花率预计达 85%，周末实行限流', time: '10 分钟前' },
    { icon: 'BirdIcon', color: '#82d5bb', title: '翠湖湿地观鸟名额放出', text: '本周六上午场观鸟屋还剩 6 个名额', time: '2 小时前' },
    { icon: 'BeeIcon', color: '#f7cd67', title: '萤火谷预约即将开始', text: '6 月萤火虫季名额将于本周三 20:00 放出', time: '昨天' },
];
